### ISSUE TITLE
[Feature] Deafen command, prevent player(s) from receiving messages.

### ISSUE THREAD

**Issue by Laarryy** [Hexaoxide/Carbon#100]
### Proposed Feature Description:
the /deafen command basically

### Proposed Feature Functionality:

would stop people from receiving messages. as if chat died

**Comment by Draycia** [comment]
`/deafen chat` deafens the entirety of chat
`/deafen user <user>` deafens specific users

designed with determinism in mind, might take a look at some of my syntaxes in the future and make them slightly more verbose for the sake of clarity and consistency. LuckPerms command syntaxes are an example. Everything is so consistent, I can easily use commands that I've never used before with relative ease because I can predict the argument layout.

**Comment by Draycia** [comment]
As Camm brought up, some way for staff to bypass deafen would be ideal.

**Comment by Draycia** [comment]
> Camm
> Or just have a config option for it, let each server decide?
`deafen-persists-on-logout: true`
