### ISSUE TITLE
[Bug] Configurations loading as dumb format instead of neat YAML.

### ISSUE THREAD

**Issue by CodeByCam** [Hexaoxide/Carbon#118]
Default config is loading like [this](https://paste.helpch.at/riyixesepe.yaml).
Have edited it to be correct(?) YAML [here](https://paste.helpch.at/initahifop.yaml), however, it does reset back to the skewed format on restart.

It seems the same for the other files, I'll update this issue with them corrected.

**Comment by Laarryy** [comment]
fOlLoW tHe tEmPlAtE

**Comment by CodeByCam** [comment]
> fOlLoW tHe tEmPlAtE

no

**Comment by CodeByCam** [comment]
[channels.yml](https://paste.helpch.at/ucasomuvez.yaml)
commands.yml looks fine.
[language.yml](https://paste.helpch.at/vubuhurono.yaml)
[moderation.yml](https://paste.helpch.at/povanubufu.yaml)

Did notice inconsistencies of strings being encased with single-quotes in some parts but not all, haven't done anything regarding that though - just corrected the layout.

**Comment by zml2008** [comment]
This is expected behaviour for automatic node style selection -- YAML supports a few different ways of specifying collections. This can be changed in current Configurate by setting the `nodeStyle` on the builder to `BLOCK`.

The inconsistencies with quoting are a snakeyaml thing -- probably because of the `[` and `]` characters, which are also used to mark YAML lists. Configurate 4.1 will let you make everything quoted if desired -- but I don't think I can override the library's cautiousness around quoting things that might not entirely need to be quoted.

**Comment by Draycia** [comment]
I'd rather it always quote anyway. I prefer consistency over convenient
inconsistency.

**Comment by Draycia** [comment]
fixed
